version: '3.1'

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: db_user
      MONGO_INITDB_ROOT_PASSWORD: db_pass
      MONGO_INITDB_DATABASE: RustDB
    ports:
      - 8081:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - dbdata6:/data/db
volumes:
  dbdata6: